// react-demo/src/components/NavBar.jsx
import { Link, useLocation } from 'react-router-dom';

function NavBar() {
  const location = useLocation();

  return (
    <>
      <nav className="text-center text-2xl grid grid-cols-8">
        <Link
          to={`/${location.pathname === '/' ? 'floating-bubble' : ''}`}
          class="hover:underline cols-span-1"
        >
          {location.pathname === '/' ? 'floating-bubble' : 'home'}
        </Link>
      </nav>
    </>
  );
}

export default NavBar;

// vue-demo/src/components/NavBar.vue
<template>
  <nav class="text-center text-2xl grid grid-cols-8">
    <RouterLink
      :to="`/${route.path === '/' ? 'floating-bubble' : ''}`"
      class="hover:underline cols-span-1"
      >{{ route.path === '/' ? 'floating-bubble' : 'home' }}</RouterLink
    >
  </nav>
</template>

<script setup>
import { RouterLink, useRoute } from 'vue-router';

const route = useRoute();
</script>
